<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<style type="text/css">
.creat_db {width:100%;height:100%;display:flex;flex-direction: column; align-items: center;justify-content: center;}
.creat_db h3 {margin:0;font-size:36px;}
button {width:50%;padding:1.3em;color:#fff;border:none;background-color:#008be4;margin-top:20px}
.display {flex-direction: column; align-items: center;}
@keyframes ldio-f4q98aymxp7 {
  0% { background: #013b4c }
  12.5% { background: #013b4c }
  12.625% { background: #0eabfc }
  100% { background: #0eabfc }
}
.ldio-f4q98aymxp7 div {
  position: absolute;
  width: 20px;
  height: 20px;
  background: #0eabfc;
  animation: ldio-f4q98aymxp7 1s linear infinite;
}
.loadingio-spinner-blocks-oh4cvvsssya {
  width: 50px;
  height: 50px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-f4q98aymxp7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.5);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-f4q98aymxp7 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
<div class="creat_db">
	<h3>RainDrop License</h3>
	<div id="btn_create_db" class="display" style="text-align: center;">
		<p>Press the button to create a raindrop database.</p>
		<button style=""  onclick="create_database();">Create database</button>
	</div>
	<div style="display:none" class="display" id="img_loading" style="padding:1em">
		<p>Creating database...</p>
		<div class="loadingio-spinner-blocks-oh4cvvsssya" style="margin-top:20px">
			<div class="ldio-f4q98aymxp7">
				<div style='left:16px;top:16px;animation-delay:0s'></div>
				<div style='left:40px;top:16px;animation-delay:0.125s'></div>
				<div style='left:64px;top:16px;animation-delay:0.25s'></div>
				<div style='left:16px;top:40px;animation-delay:0.875s'></div>
				<div style='left:64px;top:40px;animation-delay:0.375s'></div>
				<div style='left:16px;top:64px;animation-delay:0.75s'></div>
				<div style='left:40px;top:64px;animation-delay:0.625s'></div>
				<div style='left:64px;top:64px;animation-delay:0.5s'></div>
			</div>
		</div>
	</div>
	<div id="btn_close_popup" class="display" style="display:none;">
		<p>Database creation is complete.</p>
		<button class=""  onclick="window_close();">Done</button>
	</div>
</div>

<script>

function create_database() {

	$("#btn_create_db").css("display", "none");
	$("#img_loading").css("display", "flex");

	$.ajax({
	url: 'ajax.action.license.php',
	type: 'POST',
	data: {
	'type':'_raindrop'
	},
	dataType: 'html',
	success: function (data) {
	//alert(data);
	if(data == "suc"){
	$("#img_loading").css("display", "none");
	$("#btn_close_popup").css("display", "flex");
	}
	}
	});



}

function window_close(){
	opener.parent.location.reload();
	window.close();
}
</script>
